### ISSUE TITLE
Version 3.0 Local PWA Checklist

### ISSUE THREAD

**Issue by Lyrenhex** [Lyrenhex/eos#6]
For v3, the direction has changed to a local, non-externally-supported system wherein the only server required is a web server to download the app PWA files from.

- [x] Remove all server requests;
- [x] Implement the user data to be stored locally (LocalStorage);
- [x] Remove the login / registration UI;
- [x] Remove chat functionality;
- [x] Implement a data import function, allowing users to export and import their data as necessary (eg, changing devices).
- [x] Make the year graphs work (biggest difficulty likely to be the fact that we now have an indefinite number of years that we're saving).

## Notes:

- No need for internet connection after initial client resource download; after the PWA files are downloaded, it will work *perfectly* regardless of internet status.
- No chat functionality. In practise, the initial implementation was improper and didn't often work as expected, so considerable work was needed. Given a lack of time to focus on maintaining this function (in particular, moderation), it will be removed entirely. (Should demand be sufficient, it may return in a future version after more time is available to support the feature.)
- If we use LocalStorage, then data exporting will need a different implementation. I'm keen on keeping the JSON representation, though, so we can simply export a JSON object and parse that into LocalStorage for export/import.
